// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Ye21-sWW83Zwd_Nh_kvkL6KlxJNEOzQ',
    appId: '1:565403363230:web:220726cfb9302edf43188f',
    messagingSenderId: '565403363230',
    projectId: 'cantorean-6d0cd',
    authDomain: 'cantorean-6d0cd.firebaseapp.com',
    storageBucket: 'cantorean-6d0cd.appspot.com',
    measurementId: 'G-4FVZSL1ZHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOejsX2H-RH5vibFpmrS1xDpkn2BYMV3I',
    appId: '1:565403363230:android:25c56c34bc9c7cb743188f',
    messagingSenderId: '565403363230',
    projectId: 'cantorean-6d0cd',
    storageBucket: 'cantorean-6d0cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmTFyxbeib5oQ6Z9ejx06aG1SKPYbNA0',
    appId: '1:565403363230:ios:1c2282543ccad95943188f',
    messagingSenderId: '565403363230',
    projectId: 'cantorean-6d0cd',
    storageBucket: 'cantorean-6d0cd.appspot.com',
    iosClientId: '565403363230-ibm77pr85bm823csvmre5elqdji29sjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cantorean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdmTFyxbeib5oQ6Z9ejx06aG1SKPYbNA0',
    appId: '1:565403363230:ios:1c2282543ccad95943188f',
    messagingSenderId: '565403363230',
    projectId: 'cantorean-6d0cd',
    storageBucket: 'cantorean-6d0cd.appspot.com',
    iosClientId: '565403363230-ibm77pr85bm823csvmre5elqdji29sjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cantorean',
  );
}
